/*
 * Put the 'run' function, 'Config' structure and the 'new' function associated with 'Config' into the lib.rs file
 * Note: Functions, structures and their internal fields must be pub
 */
use std::error::Error;
use std::fs;

pub fn run(config: Config) -> Result<(), Box<dyn Error>> {
    /*
     * Error handling needs to be improved. If 'expect' is called, it will trigger a panic.
     * It is designed to return 'Result', it does not return anything on success so the first parameter is set to an empty tuple()
     * The second parameter is 'Box<dyn Error>', which means that this function returns a type that implements the 'Error' trait.
     * This means that different error types can be returned in different scenarios.
     */
    let contents =
        // The '?' operator does not panic when it encounters an error,
        // but returns the error value to the caller of the function so that it can handle it.
        fs::read_to_string(config.filename)?/*.expect("Something went wrong reading the file.")*/;

    for line in search(&config.query, &contents) {
        println!("{}", line);
    }

    Ok(()) // When no error occurs, it returns an 'Ok' variant with an empty tuple () as its internal value.
}

pub struct Config {
    pub query: String,
    pub filename: String,
}

impl Config {
    /*
     * For the use of the program rather than the problem itself,
     * use the return 'Result enumeration' to indicate whether the operation is successful or an error occurs
     * If the operation is successful it returns a 'Config' instance, otherwise it returns an error message.
     * The error message is a string literal with a static lifetime.
     */
    pub fn new(args: &[String]) -> Result<Config, &'static str> {
        if args.len() < 3 {
            // Make errors generated by the program understandable to the user
            // panic!("Not enough arguments ...");
            // Return Err instead of panic!
            return Err("Not enough arguments ...");
        }

        let query = args[1].clone();
        let filename = args[2].clone();

        // Finally, 'Config' needs to be wrapped in the 'Ok' variant
        Ok(Config { query, filename })
    }
}

pub fn search<'a>(query: &str, contents: &'a str) -> Vec<&'a str> {
    /*
     * First, iterate over each row in 'contents' and check whether the current row contains the 'query' string.
     * If it is included, put the entire line into the list of return values. If it is not included, continue to execute the loop search
     * Finally, the matching rows, that is, the result list Vector, are returned.
     *
     * The 'contents' string is multi-line. To iterate line by line, you can use the 'lines' method,
     * which returns an iterator that returns the contents line by line.
     */

    let mut results = Vec::new();

    for line in contents.lines() {
        if line.contains(query) {
            results.push(line);
        }
    }

    results
}

#[cfg(test)]
mod tests {
    use super::*; // All external content needs to be imported

    #[test]
    fn one_result() {
        let query = "duct";
        let contents = "\
Rust:
safe, fast, productive.
Pick three.";

        assert_eq!(vec!["safe, fast, productive."], search(query, contents))
    }
}
