/*
 * Put the 'run' function, 'Config' structure and the 'new' function associated with 'Config' into the lib.rs file
 * Note: Functions, structures and their internal fields must be pub
 */
use std::env;
use std::error::Error;
use std::fs;

pub fn run(config: Config) -> Result<(), Box<dyn Error>> {
    /*
     * Error handling needs to be improved. If 'expect' is called, it will trigger a panic.
     * It is designed to return 'Result', it does not return anything on success so the first parameter is set to an empty tuple()
     * The second parameter is 'Box<dyn Error>', which means that this function returns a type that implements the 'Error' trait.
     * This means that different error types can be returned in different scenarios.
     */
    let contents =
        // The '?' operator does not panic when it encounters an error,
        // but returns the error value to the caller of the function so that it can handle it.
        fs::read_to_string(config.filename)?/*.expect("Something went wrong reading the file.")*/;

    let results = if config.case_sensitive {
        search(&config.query, &contents)
    } else {
        search_case_insensitive(&config.query, &contents)
    };

    for line in results {
        println!("{}", line);
    }

    Ok(()) // When no error occurs, it returns an 'Ok' variant with an empty tuple () as its internal value.
}

pub struct Config {
    pub query: String,
    pub filename: String,
    pub case_sensitive: bool,
}

impl Config {
    /*
     * For the use of the program rather than the problem itself,
     * use the return 'Result enumeration' to indicate whether the operation is successful or an error occurs
     * If the operation is successful it returns a 'Config' instance, otherwise it returns an error message.
     * The error message is a string literal with a static lifetime.
     */
    /*
     * Improving this project with iterators.
     */
    pub fn new(mut args: std::env::Args) -> Result<Config, &'static str> {
        if args.len() < 3 {
            // Make errors generated by the program understandable to the user
            // panic!("Not enough arguments ...");
            // Return Err instead of panic!
            return Err("Not enough arguments ...");
        }

        args.next();

        // get the 1st, 2nd parameter by calling next()
        let query = match args.next() {
            Some(arg) => arg,
            None => return Err("Didn't get a query string"),
        };
        let filename = match args.next() {
            Some(arg) => arg,
            None => return Err("Didn't get a file name"),
        };
        /*
         * 'case_sensitive' from environment variables
         * Whenever the 'CASE_INSENSITIVE' environment variable appears, it is considered case-insensitive.
         * The result of env::var() is a Result, if the environment variable 'CASE_INSENSITIVE' is set,
         * then the result is wrapped in the 'Ok' variant or return an Err variant.
         * Here you only need to use the is_err method to check whether the Result has an error.
         * If this environment variable appears, no error will occur.
         * The result of the entire expression is false. Here we don’t care about the value of the environment variable,
         * we only care about whether it appears. There is no need to use 'unwrap' or 'expect' or other methods to get the value out
         */
        let case_sensitive = env::var("CASE_INSENSITIVE").is_err();

        // Finally, 'Config' needs to be wrapped in the 'Ok' variant
        Ok(Config {
            query,
            filename,
            case_sensitive,
        })
    }
}

pub fn search<'a>(query: &str, contents: &'a str) -> Vec<&'a str> {
    /*
     * First, iterate over each row in 'contents' and check whether the current row contains the 'query' string.
     * If it is included, put the entire line into the list of return values. If it is not included, continue to execute the loop search
     * Finally, the matching rows, that is, the result list Vector, are returned.
     *
     * The 'contents' string is multi-line. To iterate line by line, you can use the 'lines' method,
     * which returns an iterator that returns the contents line by line.
     */

    /*
    * let mut results = Vec::new();

    * for line in contents.lines() {
    *    if line.contains(query) {
    *       results.push(line);
    *   }
    * }
    * results
    */

    // optimization
    contents
        .lines()
        .filter(|line| line.contains(query))
        .collect()
}

pub fn search_case_insensitive<'a>(query: &str, contents: &'a str) -> Vec<&'a str> {
    /*
     * To perform case-insensitive operations, convert the search string and the search content to lowercase.
     */
    let mut results = Vec::new();
    let query = query.to_lowercase();

    for line in contents.lines() {
        if line.to_lowercase().contains(&query) {
            results.push(line);
        }
    }

    results
}

#[cfg(test)]
mod tests {
    use super::*; // All external content needs to be imported

    #[test]
    fn case_sensitive() {
        let query = "duct";
        let contents = "\
Rust:
safe, fast, productive.
Pick three.
Duct tape."; // Add 'Duct' with a capital letter to make it case-sensitive.

        assert_eq!(vec!["safe, fast, productive."], search(query, contents))
    }

    #[test]
    fn case_insensitive() {
        let query = "rUsT";
        let contents = "\
Rust:
safe, fast, productive.
Pick three.
Trust me.";

        assert_eq!(
            vec!["Rust:", "Trust me."],
            search_case_insensitive(query, contents)
        )
    }
}
