[package]
name = "ownership"
version = "0.1.0"
edition = "2024"

[dependencies]

# Add this section to specify the binary target
[[bin]]
name = "move_error"
path = "src/move_error.rs"

[[bin]]
name = "clone"
path = "src/clone.rs"

[[bin]]
name = "owner_func"
path = "src/owner_func.rs"

[[bin]]
name = "owner_return"
path = "src/owner_return.rs"

[[bin]]
name = "owner_reference"
path = "src/owner_reference.rs"

[[bin]]
name = "owner_slice"
path = "src/owner_slice.rs"
