/**
 * TypeScript Basic Types and Interface Practice
 *
 * Author:  Peile Wu
 * Email:   peile.wu.1990@gmail.com
 * Date:    2025/7/12
 * Purpose: Learning TypeScript basic types, interfaces, and utility types
 *          to gain competence for blockchain development positions.
 *
 * Day 01:  Covers user data type definitions, Omit<>, Partial<> utility types,
 *          and basic CRUD operations with type safety
 *
 * Additional: File day01_basic-types.js is generated by command:
 *             tsc day01_basic-types.ts
 *             There are 2 methods to run this file:
 *             1. use command: node day01_basic-types.js
 *             2. directly use command: npx ts-node day01_basic-types.ts
 */
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var nextUserId = 1; // Generate unique ID
var users = []; // Simple in-memory data storage
// Create User
function createUser(userData) {
    var newUser = __assign({ id: nextUserId++ }, userData);
    users.push(newUser);
    return newUser;
}
// Update User
function updateUser(id, updates) {
    var user = users.find(function (u) { return u.id === id; });
    if (!user) {
        throw new Error("User with id ".concat(id, " not found"));
    }
    Object.assign(user, updates); // Overwrite existing fields with the update object
    return user;
}
