/**
 * TypeScript Basic Types and Interface Practice
 *
 * Author:  Peile Wu
 * Email:   peile.wu.1990@gmail.com
 * Date:    2025/7/12
 * Purpose: Learning TypeScript basic types, interfaces, and utility types
 *          to gain competence for blockchain development positions.
 *
 * Day 01:  Covers user data type definitions, Omit<>, Partial<> utility types,
 *          and basic CRUD operations with type safety
 * 
 * Additional: File day01_basic-types.js is generated by command:
 *             tsc day01_basic-types.ts
 *             There are 2 methods to run this file:
 *             1. use command: node day01_basic-types.js
 *             2. directly use command: npx ts-node day01_basic-types.ts
 */

// Exercise: Defining types for user data
interface User {
  id: number;
  name: string;
  email: string;
  isActive: boolean;
  tags?: string[];
}

let nextUserId = 1; // Generate unique ID
const users: User[] = []; // Simple in-memory data storage

// Create User
function createUser(userData: Omit<User, "id">): User {
  const newUser: User = {
    id: nextUserId++,
    ...userData,
  };
  users.push(newUser);
  return newUser;
}

// Update User
function updateUser(id: number, updates: Partial<User>): User {
  const user = users.find((u) => u.id === id);
  if (!user) {
    throw new Error(`User with id ${id} not found`);
  }

  Object.assign(user, updates); // Overwrite existing fields with the update object
  return user;
}
